'use client';

import React, { useState } from 'react';
import { AssetItem } from '../../types/agent';
import {
  Image as ImageIcon,
  Volume2,
  Film,
  Layers,
  Maximize2,
  X,
  Play,
  Sparkles,
} from 'lucide-react';

interface AssetPreviewStreamProps {
  assets: AssetItem[];
}

export default function AssetPreviewStream({ assets }: AssetPreviewStreamProps) {
  const [filterType, setFilterType] = useState<'all' | 'image' | 'audio' | 'video'>('all');
  const [activeLightboxImage, setActiveLightboxImage] = useState<string | null>(null);

  const filteredAssets = assets.filter((a) => filterType === 'all' || a.type === filterType);

  const counts = {
    all: assets.length,
    image: assets.filter((a) => a.type === 'image').length,
    audio: assets.filter((a) => a.type === 'audio').length,
    video: assets.filter((a) => a.type === 'video').length,
  };

  return (
    <div className="w-full rounded-2xl bg-slate-900/90 backdrop-blur-xl border border-slate-800 p-5 shadow-2xl space-y-5">
      {/* Stream Header */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 border-b border-slate-800/80 pb-4">
        <div className="flex items-center gap-2.5 min-w-0">
          <span className="p-2 rounded-xl bg-orange-500/10 border border-orange-500/20 text-orange-400 shrink-0">
            <Layers className="w-4 h-4" />
          </span>
          <div className="min-w-0">
            <h3 className="text-base sm:text-lg font-bold text-slate-100 tracking-tight whitespace-nowrap">
              Live Asset Stream
            </h3>
            <p className="text-xs text-slate-400 mt-0.5 truncate">
              Real-time visual and audio output generated by agent workers
            </p>
          </div>
        </div>

        {/* Filter Tabs */}
        <div className="flex flex-wrap items-center gap-1 bg-slate-950 p-1 rounded-xl border border-slate-800 text-xs shrink-0">
          <button
            onClick={() => setFilterType('all')}
            className={`px-3 py-1.5 rounded-lg font-semibold transition ${
              filterType === 'all'
                ? 'bg-slate-800 text-amber-400 shadow-sm'
                : 'text-slate-400 hover:text-slate-200'
            }`}
          >
            All ({counts.all})
          </button>
          <button
            onClick={() => setFilterType('image')}
            className={`px-3 py-1.5 rounded-lg font-semibold flex items-center gap-1 transition ${
              filterType === 'image'
                ? 'bg-slate-800 text-amber-400 shadow-sm'
                : 'text-slate-400 hover:text-slate-200'
            }`}
          >
            <ImageIcon className="w-3.5 h-3.5" />
            Images ({counts.image})
          </button>
          <button
            onClick={() => setFilterType('audio')}
            className={`px-3 py-1.5 rounded-lg font-semibold flex items-center gap-1 transition ${
              filterType === 'audio'
                ? 'bg-slate-800 text-amber-400 shadow-sm'
                : 'text-slate-400 hover:text-slate-200'
            }`}
          >
            <Volume2 className="w-3.5 h-3.5" />
            Audio ({counts.audio})
          </button>
          <button
            onClick={() => setFilterType('video')}
            className={`px-3 py-1.5 rounded-lg font-semibold flex items-center gap-1 transition ${
              filterType === 'video'
                ? 'bg-slate-800 text-amber-400 shadow-sm'
                : 'text-slate-400 hover:text-slate-200'
            }`}
          >
            <Film className="w-3.5 h-3.5" />
            Video ({counts.video})
          </button>
        </div>
      </div>

      {/* Asset Grid */}
      {filteredAssets.length === 0 ? (
        <div className="py-10 flex flex-col items-center justify-center text-center text-slate-500 border border-dashed border-slate-800/80 rounded-xl">
          <Sparkles className="w-7 h-7 mb-2 stroke-[1.5] text-slate-600 animate-pulse" />
          <p className="text-sm font-medium text-slate-400">No assets produced yet</p>
          <p className="text-xs text-slate-500 mt-1 max-w-sm">
            Generated narration audio, 16:9 scene visuals, and final video will stream here dynamically.
          </p>
        </div>
      ) : (
        <div
          className="grid gap-4 relative"
          style={{ gridTemplateColumns: 'repeat(auto-fill, minmax(220px, 1fr))' }}
        >
          {filteredAssets.map((asset) => (
            <div
              key={asset.id}
              className={`group relative rounded-xl bg-slate-950 border overflow-hidden transition-all duration-300 min-w-[220px] ${
                asset.type === 'video'
                  ? 'border-amber-500/50 ring-1 ring-amber-500/20 col-span-full'
                  : 'border-slate-800/80 hover:border-slate-700'
              }`}
            >
              {/* Asset Card Header */}
              <div className="p-3 bg-slate-950/80 border-b border-slate-900 flex items-center justify-between text-xs gap-2">
                <div className="flex items-center gap-2 truncate min-w-0">
                  {asset.type === 'image' && <ImageIcon className="w-4 h-4 text-emerald-400 shrink-0" />}
                  {asset.type === 'audio' && <Volume2 className="w-4 h-4 text-sky-400 shrink-0" />}
                  {asset.type === 'video' && <Film className="w-4 h-4 text-amber-400 shrink-0 animate-pulse" />}
                  <span className="font-semibold text-slate-200 truncate">{asset.title}</span>
                </div>
                <span className="text-[10px] font-mono text-slate-400 shrink-0">
                  {asset.timestamp}
                </span>
              </div>

              {/* Asset Content Render */}
              <div className="p-3">
                {asset.type === 'image' && (
                  <div className="relative aspect-video rounded-lg overflow-hidden bg-slate-900 border border-slate-800 group/img">
                    {/* eslint-disable-next-next/no-img-element */}
                    <img
                      src={asset.url}
                      alt={asset.title}
                      className="w-full h-full object-cover transition-transform duration-500 group-hover/img:scale-105"
                      onError={(e) => {
                        // Fallback placeholder if image load fails
                        (e.target as HTMLImageElement).src =
                          'https://placehold.co/1920x1080/0f172a/f59e0b?text=Visual+Scene+Rendering';
                      }}
                    />
                    <button
                      onClick={() => setActiveLightboxImage(asset.url)}
                      className="absolute inset-0 bg-slate-950/40 opacity-0 group-hover/img:opacity-100 flex items-center justify-center text-slate-100 transition-opacity"
                    >
                      <span className="p-2 rounded-full bg-slate-900/80 backdrop-blur border border-slate-700">
                        <Maximize2 className="w-5 h-5 text-amber-400" />
                      </span>
                    </button>
                  </div>
                )}

                {asset.type === 'audio' && (
                  <div className="space-y-2 py-1">
                    <audio
                      src={asset.url}
                      controls
                      className="w-full h-9 rounded-lg border border-slate-800 accent-amber-500"
                    />
                  </div>
                )}

                {asset.type === 'video' && (
                  <div className="space-y-3">
                    <div className="relative aspect-video rounded-xl overflow-hidden bg-slate-950 border border-slate-800 shadow-xl">
                      <video
                        src={asset.url}
                        controls
                        className="w-full h-full object-contain"
                        poster="https://placehold.co/1920x1080/020617/f59e0b?text=Documentary+Ready"
                      />
                    </div>
                  </div>
                )}
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Lightbox Image Modal */}
      {activeLightboxImage && (
        <div
          className="fixed inset-0 z-50 bg-slate-950/90 backdrop-blur-md flex items-center justify-center p-4"
          onClick={() => setActiveLightboxImage(null)}
        >
          <div
            className="relative max-w-5xl max-h-[90vh] rounded-2xl bg-slate-900 border border-slate-800 p-2 shadow-2xl"
            onClick={(e) => e.stopPropagation()}
          >
            <button
              onClick={() => setActiveLightboxImage(null)}
              className="absolute top-4 right-4 p-2 rounded-full bg-slate-950/80 text-slate-400 hover:text-slate-100 transition z-10 border border-slate-800"
            >
              <X className="w-5 h-5" />
            </button>
            {/* eslint-disable-next-next/no-img-element */}
            <img
              src={activeLightboxImage}
              alt="High Res Preview"
              className="max-w-full max-h-[85vh] rounded-xl object-contain"
            />
          </div>
        </div>
      )}
    </div>
  );
}
